variable "project_id" {
  description = "GCP project ID."
  type        = string
}

# tflint-ignore: terraform_unused_declarations
variable "region" {
  description = "GCP region (accepted for compatibility with yaml_to_tfvars.py)."
  type        = string
  default     = null
}

variable "alert_policy" {
  description = "Alert configuration array generated by project.yaml"
  type        = any
  default = {
    spec = []
  }
}

variable "alert_policy_default" {
  description = "Default settings for the alert policy resources"
  type = object({
    metric_name             = optional(string)
    custom_metric_filter    = optional(string)
    create_metric           = optional(bool)
    custom_metric_kind      = optional(string)
    custom_metric_type      = optional(string)
    alert_filter            = optional(string)
    alert_combiner          = optional(string)
    alert_duration          = optional(string)
    alert_threshold         = optional(string)
    alert_alignment         = optional(string)
    alert_comparison        = optional(string)
    alert_aligner           = optional(string)
    alert_doc               = optional(string)
    alert_reducer           = optional(string)
    group_by_fields         = optional(list(string))
    percent                 = optional(string)
    trigger_count           = optional(string)
    evaluation_missing_data = optional(string)
    notification_channels   = optional(list(string))
    auto_close_duration     = optional(string)
  })
  default = {
    metric_name             = ""
    custom_metric_filter    = ""
    create_metric           = false
    custom_metric_kind      = ""
    custom_metric_type      = ""
    alert_filter            = ""
    alert_combiner          = "OR"
    alert_duration          = "0s"
    alert_threshold         = "0"
    alert_alignment         = ""
    alert_comparison        = ""
    alert_aligner           = ""
    alert_doc               = ""
    alert_reducer           = ""
    group_by_fields         = []
    percent                 = "0"
    trigger_count           = "0"
    evaluation_missing_data = ""
    notification_channels   = []
    auto_close_duration     = "604800s"
  }
}
