variable "project_id" {
  description = "GCP project ID."
  type        = string
}

# tflint-ignore: terraform_unused_declarations
variable "region" {
  description = "GCP region (accepted for compatibility with yaml_to_tfvars.py)."
  type        = string
  default     = null
}

variable "notification_channel" {
  description = "Notification channel configuration array generated by project.yaml"
  type        = any
  default = {
    spec = []
  }
}

variable "notification_channel_default" {
  description = "Default settings for the notification channel resources"
  type = object({
    name                 = optional(string)
    display_name         = optional(string)
    type                 = optional(string)
    email_address        = optional(string)
    finops_resource_type = optional(string)
    labels               = optional(map(string))
  })
  default = {
    name                 = null
    display_name         = null
    type                 = "email"
    email_address        = null
    finops_resource_type = "notification_channel"
    labels               = {}
  }
}
